#!/usr/bin/env python3
"""Render the PicklesToys favicon rasters from site/favicon.svg's geometry.

Why this exists rather than a one-off export: the site is dependency-free by
policy (constitution Principle 7, enforced by tests/test_site.sh T-060..T-063),
so there is no image toolchain in this repo and no Pillow/cairosvg to lean on.
This module draws the same three shapes the SVG describes, using the standard
library alone, so the rasters can be regenerated by anyone who clones the repo.

The geometry below is a transcription of site/favicon.svg. If you edit the SVG,
edit the SHAPES table to match and re-run:

    python tools/make_favicon.py

Outputs (all under site/):
    favicon.ico          32x32, PNG-encoded inside an ICO container
    apple-touch-icon.png 180x180, opaque (iOS composites no alpha)

Anti-aliasing is 4x4 supersampled coverage per pixel. That is slow in pure
Python and completely fine at these sizes.
"""
from __future__ import annotations

import math
import struct
import zlib
from pathlib import Path

# --- Geometry, in the SVG's 64x64 user space -----------------------------

ORANGE = (0xC8, 0x43, 0x1B)   # Brine Orange  — the badge
CREAM = (0xFB, 0xF3, 0xE4)    # paper         — lid and jar body
DILL = (0x5E, 0x8C, 0x1E)     # Dill Green    — the pickle

VIEWBOX = 64.0
SUPERSAMPLE = 4


def rounded_rect(x0, y0, x1, y1, r_tl, r_tr, r_br, r_bl):
    """Coverage predicate for a rectangle with per-corner radii."""

    def inside(px, py):
        if px < x0 or px > x1 or py < y0 or py > y1:
            return False
        # Each corner: if the point is inside the corner's bounding square,
        # it must also fall within the radius of that corner's centre.
        for cx, cy, r, qx, qy in (
            (x0 + r_tl, y0 + r_tl, r_tl, -1, -1),
            (x1 - r_tr, y0 + r_tr, r_tr, 1, -1),
            (x1 - r_br, y1 - r_br, r_br, 1, 1),
            (x0 + r_bl, y1 - r_bl, r_bl, -1, 1),
        ):
            if r <= 0:
                continue
            if (qx < 0 and px < cx or qx > 0 and px > cx) and (
                qy < 0 and py < cy or qy > 0 and py > cy
            ):
                return (px - cx) ** 2 + (py - cy) ** 2 <= r * r
        return True

    return inside


def rotated_ellipse(cx, cy, rx, ry, degrees):
    """Coverage predicate for an ellipse rotated about its own centre."""
    theta = math.radians(-degrees)
    cos_t, sin_t = math.cos(theta), math.sin(theta)

    def inside(px, py):
        dx, dy = px - cx, py - cy
        ux = dx * cos_t - dy * sin_t
        uy = dx * sin_t + dy * cos_t
        return (ux / rx) ** 2 + (uy / ry) ** 2 <= 1.0

    return inside


# Painter's order, matching the SVG's document order.
SHAPES = [
    # Badge: rect width=64 height=64 rx=14
    (ORANGE, rounded_rect(0, 0, 64, 64, 14, 14, 14, 14)),
    # Lid: rect x=21 y=9 width=22 height=8 rx=3
    (CREAM, rounded_rect(21, 9, 43, 17, 3, 3, 3, 3)),
    # Jar body: square shoulders at y=20, base rounded r=9, bottom at y=56
    (CREAM, rounded_rect(16, 20, 48, 56, 0, 0, 9, 9)),
    # Pickle: ellipse cx=32 cy=37 rx=7 ry=12 rotate(-13)
    (DILL, rotated_ellipse(32, 37, 7, 12, -13)),
]


def render(size: int, opaque: bool) -> bytes:
    """Render to raw RGBA rows, supersampled. Returns PNG bytes."""
    scale = VIEWBOX / size
    step = 1.0 / SUPERSAMPLE
    samples = SUPERSAMPLE * SUPERSAMPLE
    rows = bytearray()

    for py in range(size):
        rows.append(0)  # PNG per-row filter byte: 0 = None
        for px in range(size):
            # Accumulate colour and alpha over the subsample grid.
            acc_r = acc_g = acc_b = 0.0
            hits = 0
            for sy in range(SUPERSAMPLE):
                for sx in range(SUPERSAMPLE):
                    ux = (px + (sx + 0.5) * step) * scale
                    uy = (py + (sy + 0.5) * step) * scale
                    colour = None
                    for rgb, inside in SHAPES:
                        if inside(ux, uy):
                            colour = rgb
                    if colour is not None:
                        acc_r += colour[0]
                        acc_g += colour[1]
                        acc_b += colour[2]
                        hits += 1

            if hits == 0:
                # Outside the badge. iOS ignores alpha and composites on
                # black, so the touch icon is flattened onto the brand
                # colour instead of left transparent.
                rows.extend(ORANGE if opaque else (0, 0, 0))
                rows.append(255 if opaque else 0)
                continue

            r = round(acc_r / hits)
            g = round(acc_g / hits)
            b = round(acc_b / hits)
            alpha = hits / samples

            if opaque or alpha >= 1.0:
                if alpha < 1.0:
                    # Blend the partial edge against the badge colour.
                    r = round(r * alpha + ORANGE[0] * (1 - alpha))
                    g = round(g * alpha + ORANGE[1] * (1 - alpha))
                    b = round(b * alpha + ORANGE[2] * (1 - alpha))
                rows.extend((r, g, b))
                rows.append(255)
            else:
                rows.extend((r, g, b))
                rows.append(round(alpha * 255))

    return _png(size, size, bytes(rows))


def _png(width: int, height: int, raw: bytes) -> bytes:
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    # Bit depth 8, colour type 6 (RGBA), no interlace.
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def _ico(png_bytes: bytes, size: int) -> bytes:
    """Wrap a PNG in a single-image ICO container (Vista+ reads PNG in ICO)."""
    header = struct.pack("<HHH", 0, 1, 1)          # reserved, type=icon, count
    entry = struct.pack(
        "<BBBBHHII",
        size if size < 256 else 0,
        size if size < 256 else 0,
        0,                                          # palette size (0 = none)
        0,                                          # reserved
        1,                                          # colour planes
        32,                                         # bits per pixel
        len(png_bytes),
        6 + 16,                                     # offset past header+entry
    )
    return header + entry + png_bytes


def main() -> int:
    site = Path(__file__).resolve().parent.parent / "site"

    ico_png = render(32, opaque=False)
    (site / "favicon.ico").write_bytes(_ico(ico_png, 32))

    touch = render(180, opaque=True)
    (site / "apple-touch-icon.png").write_bytes(touch)

    for name in ("favicon.ico", "apple-touch-icon.png"):
        path = site / name
        print(f"  wrote {name:22} {path.stat().st_size:>6} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
